name: Monitor Cuba

on:
  workflow_dispatch:
  schedule:
      - cron: "15 */3 * * *"

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        ref: monitoring

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11.4'
        cache: 'pip'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -e .
        python -m pip install -r requirements.txt

    - name: Run script
      env:
        DEV_BLOB_SAS: ${{ secrets.DEV_BLOB_SAS }}
        CHD_DS_HOST: ${{ secrets.CHD_DS_HOST }}
        CHD_DS_PORT: ${{ secrets.CHD_DS_PORT }}
        CHD_DS_EMAIL_USERNAME: ${{ secrets.CHD_DS_EMAIL_USERNAME }}
        CHD_DS_EMAIL_PASSWORD: ${{ secrets.CHD_DS_EMAIL_PASSWORD }}
        CHD_DS_EMAIL_ADDRESS: ${{ secrets.CHD_DS_EMAIL_ADDRESS }}
        TEST_LIST: ${{ vars.TEST_LIST }}
        TEST_STORM: ${{ vars.TEST_STORM }}
        EMAIL_DISCLAIMER: ${{ vars.EMAIL_DISCLAIMER }}

      run: |
        python pipelines/monitor_cub.py
